### ISSUE TITLE
作者以后都不更新了吗

### ISSUE THREAD

**Issue by Gaomaxxr** [wangyi041228/mtga_hover#1]
作者以后都不更新了吗，卡牌不更新后我游戏都不会玩了。

**Comment by wangyi041228** [comment]
你好，
工具更新到VOW系列，只发布在网盘和QQ群780812745。
炼金系列和代码重构要等一阵子，不确定时间。
如有需要可以尝试其他插件。
感谢支持。

**Comment by Gaomaxxr** [comment]
感谢，刚刚已加群，打标准非常够用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangyi041228/mtga_hover"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangyi041228/mtga_hover] 作者以后都不更新了吗 (Issue #1)





 
你好，
 工具更新到VOW系列，只发布在网盘和QQ群780812745。
 炼金系列和代码重构要等一阵子，不确定时间。
 如有需要可以尝试其他插件。
 感谢支持。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
